### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by antoninbas** [rakelkar/gonetsh#13]
Hi - I wanted to check if the project is still maintained. If yes, would you be open to a PR with the following changes?
* switch from vendoring dependencies to using Go modules
* replace the current go-powershell dependency with https://github.com/antoninbas/go-powershell. This fork converts the project to Go modules and removes the dependency on juju packages (which are distributed under an LGPL v3 license, making usage in commercial products difficult)

Additionally, would you be willing to make a Github release/ create a tag after making the changes above?

Thanks

**Comment by rakelkar** [comment]
Sure happy to help with this!

**Comment by antoninbas** [comment]
@rakelkar Thanks for merging #14. Do you think you could create a Github release tag?

**Comment by rakelkar** [comment]
https://github.com/rakelkar/gonetsh/releases/tag/v0.3.2 works?

**Comment by antoninbas** [comment]
Works for me, but why not start at `v0.1.0` or something similar?
